name: Cypress Test
on: [push]
jobs:
  single:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          record: true
          working-directory: ./static
          build: yarn run mock:build
          start: yarn start
          wait-on: 'http://localhost:3000'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          DEBUG: 'cypress:*'
