name: main
on: [push]
jobs:

  build:
    name: Lint, Test, Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        goversion:
          - 1.14
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.goversion }}
      id: go

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: setup env
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: install golangci-lint
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE/bin v1.33.0
        echo "::add-path::$GITHUB_WORKSPACE/bin"
        chmod +x $GITHUB_WORKSPACE/bin/golangci-lint
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: yarn install, build, and test
      # specify --network-timeout flag for material-design-icons. See https://qiita.com/GandT/items/9c2afa82609ff6062fd3
      run: |
        yarn --cwd static install --network-timeout 600000
        yarn --cwd static lint
        yarn --cwd static test
      env:
        CI: true

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Setup
      run: make setup

    - name: Build
      run: make build
