name: main
on: [push]
jobs:

  build:
    name: Lint, Test, Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        goversion:
          - 1.14
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.goversion }}
      id: go

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: setup env
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: install golangci-lint
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE/bin v1.33.0
        echo "::add-path::$GITHUB_WORKSPACE/bin"
        chmod +x $GITHUB_WORKSPACE/bin/golangci-lint
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: yarn install, build, and test
      run: |
        yarn --cwd static install
        yarn --cwd static lint
        yarn --cwd static test
      env:
        CI: true

    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        record: true
        build: yarn build
        start: yarn start
        wait-on: http://localhost:3000
        working-directory: ./static
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Setup
      run: make setup

    - name: Build
      run: make build
