name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Setup env
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Install golangci-lint
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE/bin v1.33.0
          echo "::add-path::$GITHUB_WORKSPACE/bin"
          chmod +x $GITHUB_WORKSPACE/bin/golangci-lint
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: yarn install, build, and test
        run: |
          yarn --cwd static install
          yarn --cwd static lint
          yarn --cwd static test
        env:
          CI: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
